services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: igeo_web
    env_file:
      - ./web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: igeo_api
    env_file:
      - ./api/.env
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: igeo_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: igeo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d igeo"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
