services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: igeo_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: igeo_api
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:secret@db:5432/igeo
      - JWT_SECRET=your_jwt_secret
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: igeo_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: igeo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
